services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mlflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flask-networks

  mlflow-server:
    image: mlflow_server
    build:
      context: ./mlflow-server
    environment:
      - BACKEND_STORE_URI=postgresql://admin:password@db/mlflow
      - ARTIFACT_ROOT=/mlflow-artifacts
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - flask-networks
    command: mlflow server --backend-store-uri ${BACKEND_STORE_URI} --default-artifact-root ${ARTIFACT_ROOT} --host 0.0.0.0

  web-app:
    image: web_app_flask
    build:
      context: ./web-app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    ports:
      - "5001:5000"
    depends_on:
      - mlflow-server
      - db
    networks:
      - flask-networks

networks:
  flask-networks:
    driver: bridge

volumes:
  postgres_data:
  mlflow_artifact:
