FROM python

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY app.py /app/app.py

# Install required libraries
RUN pip install -r requirements.txt

COPY . /app

CMD ["flask", "run", "--host", "0.0.0.0"]
